name: Playwright Tests

on:
  push:
    branches: 
      - main
      - implement-CI    
  pull_request:
    branches: 
      - main
      - implement-CI   
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - Chrome-1920
          - Chrome-1366
          - Firefox-1920
          - Firefox-1366

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (${{ matrix.project }})
        run: npm run test --project='${{ matrix.project }}'
        continue-on-error: true

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots-${{ matrix.project }}
          path: test-results/**/trace.zip
